CREATE DATABASE DEPARTMENT
CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY  IDENTITY,
FULLNAME NVARCHAR (255) NOT NULL,
AGE INT CHECK(AGE>0) NOT NULL,
EMAIL NVARCHAR(255) NOT NULL UNIQUE,
SALARY FLOAT CHECK(SALARY BETWEEN 500 AND 3000) NOT NULL
)

INSERT INTO EMPLOYEE
VALUES('Simara Maharramli',20,'HFHHFDGHFH@EDU.AZ',700)
INSERT INTO EMPLOYEE
VALUES('DILARA Azizov',30,'HFDFGHHFD@EDU.AZ',600)
INSERT INTO EMPLOYEE
VALUES('HASAN Aliyev',35,'HFHHFGFD@EDU.AZ',800)
INSERT INTO EMPLOYEE
VALUES('Ahmet Agayev',23,'HFHHGFDFD@EDU.AZ',510)
SELECT*FROM EMPLOYEE

UPDATE EMPLOYEE
SET SALARY=500
WHERE ID=1

SELECT*FROM EMPLOYEE
WHERE SALARY BETWEEN 500 AND 1500

SELECT FULLNAME,EMAIL,SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC



